### ISSUE TITLE
Some small suggested improvements

### ISSUE THREAD

**Issue by scottwillmoore** [naughtona/naughtona.github.io#1]
Hey Andy, I love the website it looks great. Here is a quick list of some small improvements and feedback to help improve your website. They should all only take you a few minutes to adjust.

**Here are three critical improvements:**

You should only use the `<main>` element once per document, as specified in the [Mozzila documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main). While your website will still visually appear the same with multiple `<main>` elements, it may cause accessibility issues and make it difficult for crawlers (such as the Google) to actually know what is the main part of your page.

You should not use the HTML attribute `align="justify"` as seen throughout your document as `<p align="justify">`. Prior to the creation of CSS (late 90's), all page styles were managed through HTML such as `<p color="red" align="center">`. This obviously is not ideal and requires a lot of code duplication. Instead all modern styles should be defined in CSS with either an [inline, internal or external stylesheet](https://www.bitdegree.org/learn/inline-css). Any style defined as a HTML attribute that is not `style="..."` such as `color="..."` or `justify="..."` is considered an ancient (and terrible) practice. You should investigate the [`text-justify`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify) CSS property. I also just noticed that you use the `width=""` attribute on your images, which can also be replaced with appropriate CSS properties!

You should (generally) avoid inline CSS defined for example as `<div style="...">` and prefer an external stylesheet, but there are still certainly reasons to use inline CSS. A quick Google search should usually yield a large amount of information on when to prefer inline or external stylesheets, but I'll leave that for you to look into!

**You can also look into some other less-critical improvements such as:**

Your current navigation is mostly just inline-text, but you can definitely create something more sophisticated. Here is an article that I found that shows a pretty industry-standard navigation bar. [Styling a navigation bar using CSS](https://codetheweb.blog/style-a-navigation-bar-css/).

Experiment and make sure your website works correctly on a mobile device. I just checked and it does work well on my iPhone. You could still look into some improvements such as CSS media queries to make text and buttons bigger on mobile devices.

**Comment by naughtona** [comment]
Hey Scott, cheers for reviewing the website. I believe I have now addressed these issues. Andy
